//! Folder domain model: stable id, display name, and ordered child app ids.
//!
//! Phase 7 introduces `FolderId` and `Folder` but deliberately does not build
//! any folder UI. The model is here so Phase 8's folder feature (open/close,
//! rename, drag-to-create, drag-into-folder) has a stable, renderer-neutral
//! foundation to build on.
//!
//! Folder children are apps only in Phase 7 — folder nesting is intentionally
//! out of scope, and the normalization rules here enforce that children are
//! deduplicated app ids.

use std::fmt;

use crate::domain::app_id::AppId;

/// Stable, opaque identifier for a user-created folder.
///
/// Like [`AppId`], this is a normalized string wrapper so folder identity is
/// stable across relaunches and independent of folder display data (name,
/// children). The id is generated by [`FolderId::generate`] at creation time.
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
pub struct FolderId(String);

impl FolderId {
    /// Construct from an already-canonical id string (e.g. when reading back
    /// from persistence).
    pub fn from_normalized(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    /// Generate a fresh folder id. Uses a monotonic counter so ids are short
    /// and human-debuggable; collisions across runs are prevented because the
    /// counter is seeded from the max existing numeric suffix on load.
    pub fn generate(counter: u64) -> Self {
        Self(format!("folder-{counter}"))
    }

    /// The canonical id string.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Numeric suffix if the id was produced by [`FolderId::generate`]
    /// (format `folder-N`), used to seed the next generated id. Returns 0 for
    /// any id that does not match that shape.
    pub fn generated_index(&self) -> Option<u64> {
        self.0
            .strip_prefix("folder-")
            .and_then(|s| s.parse::<u64>().ok())
    }
}

impl fmt::Display for FolderId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl AsRef<str> for FolderId {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

impl From<FolderId> for String {
    fn from(id: FolderId) -> Self {
        id.0
    }
}

/// One user-created folder: a display name and an ordered list of child apps.
///
/// Children are `AppId`s only — folder nesting is not supported in Phase 7. The
/// order of `children` is user-owned and persists across rescans.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Folder {
    /// Stable folder identity.
    pub id: FolderId,
    /// User-editable display name. Default names are derived when a folder is
    /// created; Phase 8's rename feature owns the mutation.
    pub name: String,
    /// Ordered child app ids. Each id appears at most once (enforced by the
    /// normalization rules in [`crate::domain::launcher_state`]).
    pub children: Vec<AppId>,
}

impl Folder {
    /// Create a new empty folder with the given id and display name.
    pub fn new(id: FolderId, name: impl Into<String>) -> Self {
        Self {
            id,
            name: name.into(),
            children: Vec::new(),
        }
    }

    /// True if `app_id` is a direct child of this folder.
    pub fn contains_child(&self, app_id: &AppId) -> bool {
        self.children.iter().any(|c| c == app_id)
    }

    /// The number of children.
    pub fn child_count(&self) -> usize {
        self.children.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn app(s: &str) -> AppId {
        AppId::from_normalized(s.to_string())
    }

    #[test]
    fn generated_ids_round_trip_index() {
        let id = FolderId::generate(7);
        assert_eq!(id.as_str(), "folder-7");
        assert_eq!(id.generated_index(), Some(7));
    }

    #[test]
    fn arbitrary_normalized_ids_have_no_index() {
        let id = FolderId::from_normalized("imported-folder");
        assert_eq!(id.generated_index(), None);
    }

    #[test]
    fn folder_new_starts_empty() {
        let f = Folder::new(FolderId::generate(0), "Games");
        assert_eq!(f.name, "Games");
        assert!(f.children.is_empty());
        assert_eq!(f.child_count(), 0);
    }

    #[test]
    fn contains_child_matches_membership() {
        let mut f = Folder::new(FolderId::generate(0), "Games");
        f.children.push(app("a"));
        f.children.push(app("b"));
        assert!(f.contains_child(&app("a")));
        assert!(f.contains_child(&app("b")));
        assert!(!f.contains_child(&app("c")));
        assert_eq!(f.child_count(), 2);
    }

    #[test]
    fn folder_id_orders_lexicographically_and_displays() {
        let a = FolderId::from_normalized("folder-2");
        let b = FolderId::from_normalized("folder-10");
        // Numeric vs lexical: "folder-10" < "folder-2" lexically because '1' < '2'.
        assert!(b < a);
        assert_eq!(format!("{a}"), "folder-2");
        assert_eq!(a.as_ref(), "folder-2");
    }
}
